model:
  patch_size: 4
  hidden_size: 400
  num_hidden_layers: 1
  num_attention_heads: 1
  intermediate_size: 1600  # 4 * hidden_size
  hidden_dropout_prob: 0.0
  attention_probs_dropout_prob: 0.0
  initializer_range: 0.02
  image_size: 32
  num_classes: 10
  num_channels: 3
  qkv_bias: true 
  sr: 0.2
  sq: 0.2
  learned_spatial_querying: False
  local_querying: False
  mask_type: "circular"
  relu: False
      

params:
  wandb_name: "topovit"
  batch_size: 512
  epochs: 20
  lr: 1e-5